import Head from 'next/head'
import Image from "next/image";
import formImage from '../public/form.png'
import {useFormik} from "formik";
import * as Yup from 'yup'
import {useRouter} from "next/router";
import {motion as m} from 'framer-motion'

export default function Home() {
    //Router
    const router = useRouter()

    //Formik logics

    const formik = useFormik({
        initialValues: {
            name: '',
            email: '',
            country: 'China',
            terms: '',
        },

        //Validation

        validationSchema: Yup.object({
            name: Yup.string().max(20, 'Name must be 20 or less').required('Name is required'),
            email: Yup.string().email('Invalid email address').required('Email is required'),
            terms: Yup.array().required('Terms must be checked'),
        }),

        //Submit form
        onSubmit: (values) => {
            console.log(formik.values)
            router.push({pathname: '/success', query: values})
        }
    })


    return (
        <m.div className='absolute w-full' initial={{opacity: 0}} animate={{opacity: 1}} exit={{opacity: 0}}>
            <Head>
                <title>Create Next App</title>
                <meta className="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className='h-screen flex items-center justify-center'>
                <form onSubmit={formik.handleSubmit} className='bg-white flex rounded-lg w-1\2 font-latoReg'>
                    {/*Name*/}
                    <div className='flex-1 text-gray-700 p-10'>
                        <h1 className='text-3xl pb-2 font-latoBold'>Let's get started!</h1>
                        <p className='text-lg text-gray-500'>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>
                        <div className='mt-6 '>
                            <div className='pb-4'>
                                <label className={`block font-latoBold text-sm pb-2 ${formik.touched.name && formik.errors.name ? 'text-red-400' : ''}` } htmlFor="name">{formik.touched.name && formik.errors.name ? formik.errors.name : 'Name'}</label>
                                <input
                                    className='border-2 border-gray-500 p-2 rounded-md w-1/2 focus:outline-none focus:border-teal-500 focus:ring-1 focus:ring-teal-500'
                                    type="text" name='name' placeholder='Enter your name' value={formik.values.name}
                                    onChange={formik.handleChange} onBlur={formik.handleBlur}/>

                            </div>
                            {/*Email*/}
                            <div className='pb-4'>
                                <label className={`block font-latoBold text-sm pb-2 ${formik.touched.email && formik.errors.email ? 'text-red-400' : ''}` }>{formik.touched.email && formik.errors.email ? formik.errors.email : 'Email'}</label>
                                <input
                                    className='border-2 border-gray-500 p-2 rounded-md w-1/2 focus:outline-none focus:border-teal-500 focus:ring-1 focus:ring-teal-500'
                                    type="email" name='email' placeholder='Enter your email' value={formik.values.email}
                                    onChange={formik.handleChange} onBlur={formik.handleBlur}/>

                            </div>
                            {/*Country*/}
                            <div className='pb-4'>
                                <label className='block font-latoBold text-sm pb-2' htmlFor="country">Country</label>
                                <select name='country' value={formik.values.country} onChange={formik.handleChange}
                                        className='border-2 border-gray-500 p-2 rounded-md w-1/2 focus:outline-none focus:border-teal-500 focus:ring-1 focus:ring-teal-500'
                                >
                                    <option>China</option>
                                    <option>India</option>
                                    <option>United States</option>
                                    <option>Austria</option>
                                    <option>Bahrain</option>
                                    <option>France</option>
                                </select>
                            </div>
                            {/*Terms*/}
                            <div className='pb-4'>
                                <label className={`block font-latoBold text-sm pb-2 ${formik.touched.terms && formik.errors.terms ? 'text-red-400' : ''}` }>{formik.touched.terms && formik.errors.terms ? formik.errors.terms : 'Terms of service'}</label>
                                <div className='flex items-center gap-2'>
                                    <input type="checkbox" onChange={formik.handleChange} name='terms' value='checked'
                                           className='h-5 w-5 text-teal-500 border-2 focus:border-teal-500 focus:ring-teal-500'/>
                                    <p className='text-lg text-gray-500'>I agree to the Terms and Service that my data
                                        will be taken.</p>
                                </div>
                            </div>
                            <button type='submit'
                                    className='bg-teal-500 font-latoBold text-sm text-white py-3 mt-6 rounded-lg w-full'>Start
                                today!
                            </button>
                        </div>
                    </div>
                    <div className='flex-1 relative'>
                        <Image src={formImage} priority fill alt={'TuTuTu'} className={'object-cover rounded-lg '}/>
                    </div>

                </form>
            </main>


        </m.div>
    )
}
